
#ifndef _SRC_CONSTANTS_H_
#define _SRC_CONSTANTS_H_

#define MAX_BLK_SIZE 1000000
#define EMPTY_BLK_SIZE 1000
#define TXN_SIZE 1000
#define MIN_NEIGHBOURS 3
#define MAX_NEIGHBOURS 6

// in seconds
#define MIN_PROPAGATION_DELAY 0.01
#define MAX_PROPAGATION_DELAY 0.5
#define FAST_LINK_SPEED (100 * 1e6)
#define SLOW_LINK_SPEED (5 * 1e6)

#endif // _SRC_CONSTANTS_H_
